[project]
name = "user-manager"
version = "0.1.0"
description = "User crud with and admin interface"
authors = [
    { name = "davidade300", email = "davidade.dev@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "argon2-cffi (>=25.1.0,<26.0.0)",
    "pyjwt (>=2.13.0,<3.0.0)"
]

[tool.poetry]
packages = [{ include = "user_manager", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 80
format.quote-style = "single"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.coverage.run]
omit = [
    "*/__init__.py"
]

[tool.pyrefly]
search-path = ["src", "tests"]
project_includes = ["src", "tests"]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "time-machine (>=3.3.1,<4.0.0)",
    "pyrefly (>=1.2.0,<2.0.0)"
]
